version: '3.3'

services:
#  postgres:
#    image: postgres:13
#    environment:
#      POSTGRES_PASSWORD: postgres
#      PG_PASSWORD: postgres
#      POSTGRES_DB: hospital-test
#      PGDATA: /var/lib/postgresql/data/pgdata
#      POSTGRESQL_PGAUDIT_LOG: READ,WRITE
#      POSTGRESQL_LOG_HOSTNAME: true
#      POSTGRESQL_REPLICATION_MODE: master
#      POSTGRESQL_REPLICATION_USER: repl_user
#      POSTGRESQL_REPLICATION_PASSWORD: repl_password
#    volumes:
#      - ../../../postgress-data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"

  hospital-test:
    build: .
    image: hospital-test:latest
    container_name: hospital-test
    env_file:
      - .env
#    restart: always
#    command: "go test ./..."

